### ISSUE TITLE
Locatin UIBackgroundMode should not be required

### ISSUE THREAD

**Issue by cbrauchli** [ChunkyTofuStudios/native_geofence#1]
It is incorrect that the `location` `UIBackgroundMode` is required in order to handle goefence updates in the background. By setting `locationManager.allowsBackgroundLocationUpdates = false`, this plugin crashes when running on an iOS app without the background mode.

**Comment by orkun1675** [comment]
Can you expand a bit more on this?

> By setting `locationManager.allowsBackgroundLocationUpdates = false`, this plugin crashes when running on an iOS app without the background mode.

This is WAI. The [Apple documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/allowsbackgroundlocationupdates) states: Setting the value to [true](https://developer.apple.com/documentation/swift/true) but omitting the UIBackgroundModes key and location value in your app’s Info.plist file is a fatal error that terminates the app.

----

I've arrived at the conclusion that `UIBackgroundMode.location` is required after reading [this article](https://dwirandyh.medium.com/deep-dive-into-core-location-in-ios-geofencing-region-monitoring-7846802c968e). Is that not the case?

If so, would you consider creating a PR that removes [this line](https://github.com/ChunkyTofuStudios/native_geofence/blob/25259af60c085465352e0d1c3caa38d40ce705ee/ios/Classes/api/NativeGeofenceApiImpl.swift#L30) and `UIBackgroundMode.location` from the example app and test that combination in an emulator?

**Comment by cbrauchli** [comment]
> I've arrived at the conclusion that UIBackgroundMode.location is required after reading [this article](https://dwirandyh.medium.com/deep-dive-into-core-location-in-ios-geofencing-region-monitoring-7846802c968e). Is that not the case?

It is not the case. Apple's documentation in this area leaves a lot to be desired—I have been unable to find explicit documentation stating that the background mode is not required for geofencing, however I have also not found anything stating that it is. My testing shows that it works just fine without it, and [this StackOverflow question](https://stackoverflow.com/questions/13511340/uibackgroundmodes-location-and-significant-location-changes-with-region-monitori) supports that.

I have opened a PR.

**Comment by orkun1675** [comment]
Thanks for the StackOverflow reference!

I've tested this as well, in foreground, background, screen off, post-restart, etc. and it is working well on iOS `18.1`.

I've published version `1.0.3` which removes the dependency on `UIBackgroundModes.location`.

Please feel free to upgrade and let me know if you run into any issues in production!

**Comment by raam86** [comment]
Is this still relevant (no need for ui UIBackgroundModes.location)? The example doesn't request this permission in info.plist but the readme says you need it?

**Comment by orkun1675** [comment]
Where do you see in the README that the background mode is required?

I thought I removed it in https://github.com/ChunkyTofuStudios/native_geofence/commit/b0f66363293468eba4117075376076b37b04732d.

**Comment by raam86** [comment]
in the header 
What are the plugin requirements?
    iOS 14+ and Android API 29+. You will also need to obtain background location permission from the user.

**Comment by orkun1675** [comment]
Background location permission (aka. NSLocationAlwaysAndWhenInUseUsageDescription) **is** required.

However, `UIBackgroundModes.location` **is not** required. These are distinct permissions.
